services:
  - type: web
    name: efapro-web
    env: static
    buildCommand: git clone https://github.com/flutter/flutter.git -b stable && ./flutter/bin/flutter build web --release
    staticPublishPath: build/web
