import re

content = open('lib/data/mock_data.dart', 'r').read()

new_words_data = """  static List<Word> words = [
    Word(
      id: 'w1', word: 'Algorithm', translation: 'خوارزمية',
      usage: 'A process or set of rules to be followed in calculations or other problem-solving operations.',
      example: 'The app uses a complex algorithm to recommend videos.', emoji: '🔢',
      partOfSpeech: 'noun', synonyms: ['procedure', 'routine'], antonyms: [],
      ipa: '/ˈæl.ɡə.rɪ.ðəm/', movieQuote: '"The Matrix algorithm is a complicated set of instructions." - The Matrix',
      categoryId: 'tech', subcategoryId: 'tech_prog', levelId: 'B2',
    ),
    Word(
      id: 'w_cyber', word: 'Firewall', translation: 'جدار حماية',
      usage: 'A network security system that monitors and controls network traffic.',
      example: 'The company installed a new firewall to prevent cyber attacks.', emoji: '🧱',
      partOfSpeech: 'noun', synonyms: ['shield', 'barrier'], antonyms: [],
      ipa: '/ˈfaɪr.wɔːl/', categoryId: 'tech', subcategoryId: 'tech_cyber', levelId: 'B1',
    ),
    Word(
      id: 'w_code', word: 'Compile', translation: 'يجمع برمجيًا',
      usage: 'Convert a program into a machine-code or lower-level form in which the program can be executed.',
      example: 'It takes a few minutes to compile the codebase.', emoji: '⚙️',
      partOfSpeech: 'verb', v2: 'Compiled', v3: 'Compiled',
      synonyms: ['assemble', 'build'], antonyms: ['decompile'],
      ipa: '/kəmˈpaɪl/', categoryId: 'tech', subcategoryId: 'tech_prog', levelId: 'B2',
    ),
    Word(
      id: 'w2', word: 'Negotiate', translation: 'يتفاوض',
      usage: 'Try to reach an agreement or compromise by discussion.',
      example: 'They are trying to negotiate a new contract.', emoji: '🤝',
      partOfSpeech: 'verb', v2: 'Negotiated', v3: 'Negotiated',
      synonyms: ['discuss', 'bargain'], antonyms: ['refuse'],
      ipa: '/nəˈɡoʊ.ʃi.eɪt/', movieQuote: '"I am altering the deal. Pray I don\\'t alter it any further." - Star Wars',
      categoryId: 'business', levelId: 'C1',
    ),
    Word(
      id: 'w3', word: 'Symptom', translation: 'عَرَض',
      usage: 'A physical or mental feature which is regarded as indicating a condition of disease.',
      example: 'Fever is a common symptom of the flu.', emoji: '🤒',
      partOfSpeech: 'noun', synonyms: ['sign', 'indication'], antonyms: [],
      ipa: '/ˈsɪmp.təm/', categoryId: 'health', subcategoryId: 'health_anatomy', levelId: 'B1',
    ),
    Word(
      id: 'w_surg', word: 'Operate', translation: 'يجري عملية جراحية',
      usage: 'Perform a surgical operation.',
      example: 'The doctor will operate on him tomorrow morning.', emoji: '🥼',
      partOfSpeech: 'verb', v2: 'Operated', v3: 'Operated',
      synonyms: ['treat', 'perform surgery'], antonyms: [],
      ipa: '/ˈɑː.pə.reɪt/', categoryId: 'health', subcategoryId: 'health_pharm', levelId: 'B2',
    ),
    Word(
      id: 'w4', word: 'Itinerary', translation: 'مسار الرحلة',
      usage: 'A planned route or journey.',
      example: 'We planned a detailed itinerary for our trip to Europe.', emoji: '🗺️',
      partOfSpeech: 'noun', synonyms: ['schedule', 'plan', 'route'], antonyms: [],
      ipa: '/aɪˈtɪn.ə.rer.i/', categoryId: 'travel', levelId: 'B2',
    ),
    Word(
      id: 'w_fly', word: 'Depart', translation: 'يغادر',
      usage: 'Leave, typically in order to start a journey.',
      example: 'The flight will depart at 8 PM.', emoji: '🛫',
      partOfSpeech: 'verb', v2: 'Departed', v3: 'Departed',
      synonyms: ['leave', 'take off'], antonyms: ['arrive'],
      ipa: '/dɪˈpɑːrt/', categoryId: 'travel', levelId: 'A2',
    ),
    Word(
      id: 'w_law1', word: 'Testify', translation: 'يشهد',
      usage: 'Give evidence as a witness in a law court.',
      example: 'He was called to testify in the murder trial.', emoji: '✋',
      partOfSpeech: 'verb', v2: 'Testified', v3: 'Testified',
      synonyms: ['bear witness', 'swear'], antonyms: ['conceal'],
      ipa: '/ˈtes.tə.faɪ/', movieQuote: '"You want answers?! I think I am entitled to them!" - A Few Good Men',
      categoryId: 'law', subcategoryId: 'law_court', levelId: 'C1',
    ),
    Word(
      id: 'w_law2', word: 'Jurisdiction', translation: 'اختصاص قضائي',
      usage: 'The official power to make legal decisions and judgements.',
      example: 'The court has no jurisdiction in this case.', emoji: '⚖️',
      partOfSpeech: 'noun', synonyms: ['authority', 'control'], antonyms: [],
      ipa: '/ˌdʒʊr.ɪsˈdɪk.ʃən/', categoryId: 'law', subcategoryId: 'law_court', levelId: 'C1',
    ),
    Word(
      id: 'w_econ', word: 'Fluctuate', translation: 'يتذبذب',
      usage: 'Rise and fall irregularly in number or amount.',
      example: 'The stock market tends to fluctuate wildly.', emoji: '📉',
      partOfSpeech: 'verb', v2: 'Fluctuated', v3: 'Fluctuated',
      synonyms: ['vary', 'change'], antonyms: ['stabilize'],
      ipa: '/ˈflʌk.tʃu.eɪt/', categoryId: 'economy', levelId: 'C1',
    ),
    Word(
      id: 'w_veg', word: 'Broccoli', translation: 'بروكلي',
      usage: 'A cultivated variety of cabbage bearing heads of green or purplish flower buds.',
      example: 'I like to eat steamed broccoli for dinner.', emoji: '🥦',
      partOfSpeech: 'noun', synonyms: [], antonyms: [],
      ipa: '/ˈbrɑː.kəl.i/', categoryId: 'food', subcategoryId: 'food_veg', levelId: 'A2',
    ),
    Word(
      id: 'w_fam1', word: 'Sibling', translation: 'شقيق/شقيقة',
      usage: 'Each of two or more children or offspring having one or both parents in common.',
      example: 'I have three siblings: two brothers and one sister.', emoji: '👧👦',
      partOfSpeech: 'noun', synonyms: ['brother', 'sister'], antonyms: ['only child'],
      ipa: '/ˈsɪb.lɪŋ/', categoryId: 'family', levelId: 'B1',
    ),
    Word(
      id: 'w_fam2', word: 'Inherit', translation: 'يَرِث',
      usage: 'Receive money, property, or a title as an heir at the death of the previous holder.',
      example: 'She will inherit a large fortune from her grandfather.', emoji: '📜',
      partOfSpeech: 'verb', v2: 'Inherited', v3: 'Inherited',
      synonyms: ['receive', 'take over'], antonyms: ['lose', 'give away'],
      ipa: '/ɪnˈher.ɪt/', categoryId: 'family', levelId: 'B2',
    ),
    Word(
      id: 'w_edu', word: 'Comprehend', translation: 'يستوعب/يفهم',
      usage: 'Grasp mentally; understand.',
      example: 'He couldn\\'t comprehend the complexity of the math problem.', emoji: '🧠',
      partOfSpeech: 'verb', v2: 'Comprehended', v3: 'Comprehended',
      synonyms: ['understand', 'grasp'], antonyms: ['misunderstand'],
      ipa: '/ˌkɑːm.prəˈhend/', categoryId: 'education', levelId: 'B2',
    ),
    Word(
      id: 'w_spo', word: 'Compete', translation: 'يتنافس',
      usage: 'Strive to gain or win something by defeating or establishing superiority over others.',
      example: 'Several teams will compete for the championship.', emoji: '🏆',
      partOfSpeech: 'verb', v2: 'Competed', v3: 'Competed',
      synonyms: ['contest', 'contend'], antonyms: ['cooperate'],
      ipa: '/kəmˈpiːt/', categoryId: 'sports', levelId: 'B1',
    ),
    Word(
      id: 'w_wea', word: 'Drizzle', translation: 'رذاذ/مطر خفيف',
      usage: 'Light rain falling in very fine drops.',
      example: 'It was starting to drizzle, so she grabbed her umbrella.', emoji: '🌧️',
      partOfSpeech: 'verb', v2: 'Drizzled', v3: 'Drizzled',
      synonyms: ['sprinkle', 'spit'], antonyms: ['pour'],
      ipa: '/ˈdrɪz.əl/', categoryId: 'weather', levelId: 'B2',
    ),
    Word(
      id: 'w_emo', word: 'Overwhelm', translation: 'يغمر/يقهر شعورياً',
      usage: 'Bury or drown beneath a huge mass.',
      example: 'She was overwhelmed by the amount of homework.', emoji: '😵',
      partOfSpeech: 'verb', v2: 'Overwhelmed', v3: 'Overwhelmed',
      synonyms: ['engulf', 'swamp'], antonyms: ['underwhelm'],
      ipa: '/ˌoʊ.vɚˈwelm/', categoryId: 'emotions', levelId: 'C1',
    ),
    Word(
      id: 'w_verb_irr1', word: 'Speak', translation: 'يتحدث',
      usage: 'Say something in order to convey information, an opinion, or a feeling.',
      example: 'Can you speak louder, please?', emoji: '🗣️',
      partOfSpeech: 'verb', v2: 'Spoke', v3: 'Spoken',
      synonyms: ['talk', 'say'], antonyms: ['listen', 'stay silent'],
      ipa: '/spiːk/', categoryId: 'daily', levelId: 'A1',
    ),
    Word(
      id: 'w_verb_irr2', word: 'Write', translation: 'يكتب',
      usage: 'Mark (letters, words, or other symbols) on a surface, typically paper.',
      example: 'I need to write a letter to my friend.', emoji: '✍️',
      partOfSpeech: 'verb', v2: 'Wrote', v3: 'Written',
      synonyms: ['pen', 'draft'], antonyms: ['read'],
      ipa: '/raɪt/', categoryId: 'daily', levelId: 'A1',
    ),
    Word(
      id: 'w_verb_irr3', word: 'Forget', translation: 'ينسى',
      usage: 'Fail to remember.',
      example: 'Don\\'t forget your keys!', emoji: '🤷',
      partOfSpeech: 'verb', v2: 'Forgot', v3: 'Forgotten',
      synonyms: ['blank', 'overlook'], antonyms: ['remember'],
      ipa: '/fɚˈɡet/', categoryId: 'emotions', levelId: 'A2',
    ),
  ];
}"""

# Using regex to replace the entire words array block
new_content = re.sub(r'  static List<Word> words = \[.*?\];\n\}', new_words_data, content, flags=re.DOTALL)
open('lib/data/mock_data.dart', 'w').write(new_content)
